### ISSUE TITLE
Duda como incluir gribs descargados en el geoserver

### ISSUE THREAD

**Issue by 0neTX** [geotekne-argentina/ncep-weather-geoserver#1]
Hola,

Estoy buscando como incluir información meteorológica descargada como GRIB en un servidor GeoServer cuando me he encontrado con tu proyecto que parece que se ajusta perfectamente a lo que busco. 

He estado haciendo algunas pruebas y he incluido en contenedor `ncep-weather-worker` en el [docker-compose](https://github.com/0neTX/ncep-weather-geoserver/blob/main/docker-compose.yml)

```yaml
  ncep-weather-worker:
      volumes:
          - ./data/nomads_ncep_noaa:/tmp/datastore
          - ./conf/ncep-weather-worker/config.sh:/scripts/config.sh
      container_name: ncep-weather-worker
      image: geotekne/ncep-weather-worker:1.0.0
```

Con su ejecución he conseguido que se descarguen varios ficheros .grib (usando la configuración inicial del [config.sh](https://github.com/0neTX/ncep-weather-geoserver/blob/main/conf/ncep-weather-worker/config.sh)

Sin embargo, no tengo claro como transferir la información de estos ficheros .grib al geoserver.

Soy un poco novato con GeoServer ¿podrias ayudarme?

He intentado copiando los fichero .grib en la carpeta "geoserver/datadir/data/nomads_ncep_noaa" y el [log](https://raw.githubusercontent.com/0neTX/ncep-weather-geoserver/refs/heads/main/data/geoserver/datadir/logs/geoserver.log)  me muestra varios errores. Creo que me falta un paso intermedio por realizar.

Te agradeceria cualquier pista o ayuda. Gracias!!
